SNTWREC-187 initial commit of horizontal scrolling row replacing grid
WestdeutscherRundfunkKoeln/recommender-explorer pull request #122
Opened 2024-10-28 14:35 UTC by felixjakobkluetsch

Replaces Item Grid with scrollable rows. 
To work, cards now need a fixed width, cards width get set in the superclass of cards (can be overwritten when superclass is initialized)
Also add number of recommendations param for opensearch and pa service so result count is customizable.

2024-11-06 12:27 UTC, grusc requested changes
Die page_size sollte noch in das config schema.

2024-11-06 12:27 UTC, grusc commented on src/view/RecoExplorerApp.py
> +        self.UP_ARROW = "\u25b2"
argueably musst das keine member variable sein, könnte auch ne Konstante sein

2024-11-06 12:27 UTC, grusc commented on src/view/RecoExplorerApp.py
> +        if self.page_size <= self.page_size:
ist das nicht immer True?

2024-11-06 12:27 UTC, grusc commented on src/view/RecoExplorerApp.py
> +                    if idz == 0:
Warum treffen wir die Unterscheidung hier schon?
Ich fände es besser wenn wir die gesamte liste an add_cards_row_and_navigation_buttons übergibt und erst dor dann die unterscheidung über
```
start_card, *reco_cards = reco_cards
```
trifft. Dadurch wäre hier zumindest ein level an intendation weg

2024-11-06 12:27 UTC, grusc commented on src/view/RecoExplorerApp.py
> +        prev_button.widgets = widgets
Das wird ja nur gemacht um im on_click auf die widgets zugreifen zu können.
Können wir hier nicht einfach das on_click currien?

2024-11-11 12:59 UTC, felixjakobkluetsch commented on src/view/RecoExplorerApp.py
> +                    if idz == 0:
Bin noch weiter gegangen und habe die Row auch noch von der Navigation getrennt

2024-11-11 13:15 UTC, merged