SNTWREC-86 add text area input widget to configuration based widgets
WestdeutscherRundfunkKoeln/recommender-explorer pull request #50
Opened 2024-06-04 13:28 UTC by felixjakobkluetsch

In UI Config can be tested like this: 

-   type: 'text_area_input'
    label: 'Text'
    url_parameter: 'text'

2024-06-04 14:00 UTC, grusc requested changes
Readme solltest noch updaten. Technisch passt's!

2024-06-05 09:00 UTC, grusc requested changes

2024-06-05 09:00 UTC, grusc commented on README.md
> +### Slider Config Overview
Slider -> Text Area

2024-06-05 09:00 UTC, grusc commented on README.md
> +### Example of a Slider Widget Configuration
Slider -> Text Area

2024-06-05 09:00 UTC, grusc commented on config/schema/ui_schema.json
> +      "anyOf": [
Sind die Felder wirklich hier "anyOf" required? Verstehe nicht warum.

2024-06-05 09:25 UTC, felixjakobkluetsch commented on config/schema/ui_schema.json
> +      "anyOf": [
Nö, hab nur scheinbar nicht ganz verstanden, was das bedeutet :D Habs entfernt.

2024-06-05 09:26 UTC, felixjakobkluetsch commented on README.md
> +### Slider Config Overview
Verbessert

2024-06-05 09:26 UTC, felixjakobkluetsch commented on README.md
> +### Example of a Slider Widget Configuration
Verbessert

2024-06-05 09:31 UTC, grusc approved these changes
LGTM

2024-06-05 09:33 UTC, merged