SNTWREC-125 change visible action functionality.
WestdeutscherRundfunkKoeln/recommender-explorer pull request #58
Opened 2024-06-14 10:06 UTC by felixjakobkluetsch

Zum testen einfach config für einen Reco Filter umstellen: 

```
type: 'accordion'
label: 'Sendereihen Filter'
content:
   type: 'multi_select'
   label: 'termfilter_show'
   register_as: 'reco_filter'
   dictionary_options:
      Nur gleiche Sendereihe: 'same_theme'
      Nur andere Sendereihen: 'different_theme'
      Sendereihen auswählen: 'choose_show'
   action_option:
      choose_show: 'value_showTitel'
   type: 'multi_select'
   label: 'value_showTitel'
   register_as: 'reco_filter'
   option_default: 'showTitle'
```

2024-06-17 09:52 UTC, grusc commented
Habs lokal getestet. Funktioniert!

2024-06-17 09:54 UTC, grusc requested changes
Das UI Schema muss noch angepasst werden!

2024-06-18 07:29 UTC, felixjakobkluetsch commented on src/view/widgets/accordion_widget.py
> +        if all(isinstance(widget, pn.widgets.MultiSelect) for widget in accordion_content) and len(accordion_content) > 1:
Ja ich glaube du hast Recht. Das ist glaub ich noch von einem vorherigen Versuch stehen geblieben. Mir ist jedenfalls auch kein Grund mehr dafür eingefallen ;)

2024-06-18 07:29 UTC, felixjakobkluetsch commented on src/view/widgets/accordion_widget.py
> +                if hasattr(source_widget, "action_parameter"):
Ich habe etwas refactored

2024-06-18 07:37 UTC, grusc approved these changes
LGTM

2024-06-18 07:37 UTC, felixjakobkluetsch commented on src/view/widgets/multi_select_widget.py
> +            action_parameter = {list(pair.keys())[0]: list(pair.values())[0] for pair in config.get(c.MULTI_SELECT_ACTION_OPTION_KEY)}
Tatsächlich braucht es die (auch wenn es auf den ersten Blick was komisch aussieht). Die keys und die values für das pair kann ich sonst nicht iterieren (Habs nochmal sicherheitshalber ausprobiert)

2024-06-18 07:38 UTC, merged